[package]
name = "managing_packages"
version = "0.1.0"
authors = ["marcin.hujdus <marcin.hujdus@aptiv.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sample_module = { path = "./sample_module" }
